-- Migration 013: Weekly Monitor automation — snapshots, notifications, content packs
-- Adds week-over-week history for competitors + self metrics, the notification
-- feed (generated by the weekly cron), and the monthly content-pack store.

-- ── Richer weekly metrics (ai_rank already exists from 007) ──────────────────
ALTER TABLE dashboard_metrics ADD COLUMN IF NOT EXISTS google_score INTEGER;
ALTER TABLE dashboard_metrics ADD COLUMN IF NOT EXISTS rating        NUMERIC(2,1);
ALTER TABLE dashboard_metrics ADD COLUMN IF NOT EXISTS pdf_url       TEXT;

-- ── Full weekly snapshot (self metrics + competitor list) ────────────────────
-- One row per user per week. `snapshot` holds:
--   { score, googleScore, aiRank, rating, reviewCount, competitors:[...], campaign:{name} }
CREATE TABLE IF NOT EXISTS competitor_snapshots (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  week        DATE        NOT NULL,
  snapshot    JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, week)
);
CREATE INDEX IF NOT EXISTS idx_competitor_snapshots_user_week ON competitor_snapshots(user_id, week DESC);
ALTER TABLE competitor_snapshots ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='competitor_snapshots' AND policyname='service_role_competitor_snapshots') THEN
    CREATE POLICY "service_role_competitor_snapshots" ON competitor_snapshots
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ── Notification feed (alerts generated each Monday) ─────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  type        TEXT        NOT NULL,
  severity    TEXT        NOT NULL DEFAULT 'info',  -- info | warning | critical
  title       TEXT        NOT NULL,
  message     TEXT,
  meta        JSONB       NOT NULL DEFAULT '{}'::jsonb,
  read        BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, created_at DESC);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='notifications' AND policyname='service_role_notifications') THEN
    CREATE POLICY "service_role_notifications" ON notifications
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ── Monthly content packs (topical campaign + generated content) ─────────────
-- One row per user per calendar month (month = 'YYYY-MM').
CREATE TABLE IF NOT EXISTS content_packs (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  month          TEXT        NOT NULL,             -- 'YYYY-MM'
  campaign_name  TEXT,
  campaign_theme TEXT,
  content        JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, month)
);
CREATE INDEX IF NOT EXISTS idx_content_packs_user_month ON content_packs(user_id, month DESC);
ALTER TABLE content_packs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='content_packs' AND policyname='service_role_content_packs') THEN
    CREATE POLICY "service_role_content_packs" ON content_packs
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;
